# Site settings
title: 廉一鸣的小站
title2: LianYiMing
SEOTitle: 廉一鸣的博客
header-img: img/headimg/14.jpg
email: AGZX_lym@163.com
description:  "去他妈的真理无穷,进一步有一步的欢喜."
keyword: "廉一鸣的博客, LianYiMing, 廉一鸣, lianyiming.com,lianyiming.github.io"
#搜索引擎关键词
url: "https://www.lianyiming.com/"          
# your host, for absolute URL，rss要用，所以是你的域名
baseurl: "/"      # for example, '/blog' if your blog hosted on 'host/blog'如果是www.linyiming.com就不用。这种情况是为了应对github创建第二个page
github_repo: "https://github.com/LianYiMing/LianYiMing.github.io" # 你的github仓库

# Sidebar settings
sidebar: true # whether or not using Sidebar.
aboutSidebar: false 
#ABOUT默认隐藏侧边栏
sidebar-about-description: "Live a life you will remember"
sidebar-avatar: /img/LianYiMing.jpg      # 用绝对URL地址,也就是要在前面加上/



# RSS settings
RSS: true
# 是否开RSS(直接true就可以，不需要其他任何操作呢)
twitter_username:  agzx
#Twitter名字
zhihu_username:    32c99075e7bcda4069d856f0552b4591
#网页版知乎地址后面的字符串
github_username:    LianYiMing
#GIthub账户名字
facebook_username:  100054268065189
#用大哥您的脸书网页版主页地址最后的数字
weibo_username:  agzxlym
#微博的名字
jianshu_username: false

csdn_username: m0_49671092
#csdn网页版后面的字符串

#linkedin_username:
#用的话删掉上边的#就可以了




# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
highlighter: rouge
permalink: pretty
paginate: 7
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
anchorjs: true                          # if you want to customize anchor. check out line:181 of `post.html`


#页面的几个特效
#boolean值，要用就true，不用就false，注意空格
#
threa: false #文章动态粗线条背景
thread: false #文章动态线条+颗粒背景
#bannerUrl: "/img/headimg/" + new Date().getDay() + '.jpg'
lovemouse : true
#全局鼠标爱心
Load: true
#全局页面加载动画
FunnyTitle: true
#全局跳出页面title自动显示已崩溃
cat: true 
#全局左下角cat
cute: flase
#全局左下角看板娘
aplayer: true
#音乐
snow: true
#除了friend页面的全局头图下雪
flower: false
#页面下樱花

# Gems
# from PR#40, to support local preview for Jekyll 3.0
gems: [jekyll-paginate]




# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM                            # use Github Flavored Markdown !important



# 评论系统(不要加引号，要空一格子再输入值，前面要有两个空格，否则github会报错：在第2行有问题)
#vaLINE
valine:
  enable: true
  appId: 324CSMlwN7QYCW31WN0BOd61-gzGzoHsz
  appKey: cUgj6L8hQhKJijEUq6dyb68S


# Disqus（https://disqus.com/）
disqus_username:  
#LianYiMing （也就是你的用户名）
#{{}}和{%%}完全不一样

# Gitalk
gitalk:
  enable: false   #是否开启Gitalk评论
  clientID: 0ba0ce534eaab8f3df75                          #生成的clientID
  clientSecret: 3e24f7e6e0084eb5a906a8ac4610a1463449f196    #生成的clientSecret
  repo: LianYiMing.github.io     #仓库名称
  owner: LianYiMing    #github用户名
  admin: LianYiMing
  distractionFreeMode: true #是否启用类似FB的阴影遮罩

webpush: false
#网页通知
key: BNQ6NiuLHsmWrATJNAyeF_V9zguy7g4GJFtGv2G1D5b2j5xbhkmkxApQtk6RxsMAzKf7X_IDThjM7tAi_gFKdek
#也就是这里的key (https://app.webpushr.com/dashboard/geo-report)

# 统计

# Analytics settings
# Baidu Analytics
ba_track_id: f0079dc2c26d600c76482c2644411151

# Google Analytics
ga_track_id: 'UA-176698352-1'            # Format: UA-xxxxxx-xx
ga_domain: www.lianyiming.com               # 默认的是 auto, 这里我是自定义了的域名，你如果没有自己的域名，需要改成autoL



#外部js貌似不行欸
#页脚footer网站运行时间，这里填入大佬您贵站的生日（乱填会报错的说，，，，）
siteYear: 2020
siteMonth: 7
siteDate: 30
siteHour: 0
siteMinute: 0
siteSecond: 0

# Featured Tags
featured-tags: true                     # 是否使用首页标签
featured-condition-size:  1            # 相同标签数量大于这个数，才会出现在首页



# Progressive Web Apps
chrome-tab-theme-color: "#000000"
service-worker: true

#注意逗号！！！
page-mathjax: true
# Friends
friends: [
  {
         title: "鲸一",
         href: "https://www.saroin.com/"
     },
 {
         title: "哎呦哎呦",
         href: "https://iuiu.run/"
     },
 {
         title: "Kif Room",
         href: "https://www.kifroom.icu/#"
     },
 {
         title: "Xu Yiyang",
         href: "https://blog.xuyiyang.top/"
     },
 {
       title: "小浣熊的技术小站",
       href: "https://nimitiz.cn/"
     },
 {
       title: "从南小站",
       href: "https://ouoo.fun/"
     }, 
 {
       title: "Astics的博客",
       href: "https://astcs.gitee.io/"

     },
 {
       title: "今今今生",
       href: "https://noheart.cn"

     }, 
 {
       title: "杏铃の小本",
       href: "https://66ccff.work/"

     },
 {
       title: "Deserts",
       href: "https://deserts.io/"

     },
 {
       title: "独人欣赏",
       href: "https://www.wangyusong.cn"

     },
 {
       title: "Liumang",
       href: "https://blog.liumang.life/"

     },
 {
       title: "Eanraig",
       href: "https://eanraig.top"
     },
 {
       title: "Alsaces",
       href: "https://www.alsaces.cn"

     },
 {
       title: "Xunflash的小站",
       href: "http://www.xunflash.top/"

     },
]	 
friend1: [
 {
       title: "鲸一",
       href: "https://www.saroin.com/",
       img: "https://cdn.jsdelivr.net/gh/AJRECHO/WWW@master/uPic/user/ajrecho.jpg",
       intro: "不是忙着活，就是忙着累死"
     },
]
friend2: [
 {
       title: "XuYiyang",
       href: "https://blog.xuyiyang.top/",
       img: "https://www.lianyiming.com/img/Xu.jpg",
       intro: "大佬还未给描述呢"
     },
]
friend3: [
 {
       title: "Kif Room",
       href: "https://www.kifroom.icu/#",
       img: "https://s1.ax1x.com/2020/06/23/NUr8pQ.jpg",
       intro: "kif的树洞"
     },
]
friend4: [
 {
       title: "哎呦哎呦",
       href: "https://iuiu.run/",
       img: "https://q1.qlogo.cn/g?b=qq&nk=10963273&s=640",
       intro: "哎呦哎呦是一个关注互联网和分享网站建设·记录生活的个人博客"
     },
]
friend5: [
 {
       title: "Astics的博客",
       href: "https://astcs.gitee.io/",
       img: "https://s1.ax1x.com/2020/09/07/wn5dU0.jpg",
       intro: "一个简单的小白博客"
     },
]
friend6: [
 {
       title: "杏铃の小本",
       href: "https://66ccff.work/",
       img: "https://gitee.com/hshx123/picplus/raw/master/1595119088132.png",
       intro: "一份分享教程&游戏的博客"
     },
]
friend7: [
 {
       title: "Deserts",
       href: "https://deserts.io/",
       img: "https://www.gravatar.com/avatar/f32fc1c3f6674bfb5621a60901b5f96c?s=250&d=mm&r=x",
       intro: "大佬还未给描述呢"
     },
]
friend8: [
 {
       title: "今今今生",
       href: "https://noheart.cn",
       img: "https://noheart.cn/upload/mylife.jpg",
       intro: "医不自医，人不渡己"
     },
]
friend9: [
 {
       title: "Eanraig",
       href: "https://eanraig.top",
       img: "https://cdn.jsdelivr.net/gh/eanraig/eanraig-storage/2020/09/avatar.jpg",
       intro: "大佬还未给描述呢"
     },
]
friend10: [
 {
       title: "Liumang",
       href: "https://blog.liumang.life/",
       img: "https://img.yxyy.top/2020/09/0E049C08-5C8A-4B0E-B861-BC3258A2AC22.png",
       intro: "Liumang's Blog"
     },
]
friend11: [
 {
       title: "小浣熊的技术小站",
       href: "https://nimitiz.cn/",
       img: "https://nimitiz.cn/images/avatar.gif",
       intro: "生命不息，折腾不止"
     },
]
friend12: [
 {
       title: "独人欣赏",
       href: "https://www.wangyusong.cn",
       img: "https://www.lianyiming.com/img/head.jpg",
       intro: "摆脱了十足乏味的交际，摆脱不了群居属性"
     },
]
friend13: [
 {
       title: "Alsaces",
       href: "https://www.alsaces.cn",
       img: "https://cdn.jsdelivr.net/gh/zhangfh-cq/images/second-blog/universal/avatar.png",
       intro: "言必行，行必果"
     },
]
friend14: [
 {
       title: "从南小站",
       href: "https://ouoo.fun/",
       img: "http://cdn.mc.huluxia.net/g4/M01/51/FE/rBAAdl9njJyAWyVfAAAM7021VZU034.png",
       intro: "致我逝去的青春"
     },
]
friend15: [
 {
       title: "Xunflash的小站",
       href: "http://www.xunflash.top/",
       img: "https://s1.ax1x.com/2020/09/21/wb8qET.jpg",
       intro: "真不戳，嘿嘿"
     },
]
friend16: [
 {
       title: "Coderemarks",
       href: "http://blog.coderemarks.cn",
       img: "https://coderemarks.coding.net/p/coderemarks/d/blog/git/raw/master/7eb505f2cd077a63dddcfa8c8673cb41.jpg",
       intro: "不仅仅是代码注释，更是我人生的备注！"
     },
]
friend17: [
 {
       title: "小理の小窝",
       href: "https://www.v48v.cn/",
       img: "https://anfangd.com/2020/09/706751558.jpeg",
       intro: "生而为爷 我很抱歉"
     },
]
friend18: [
 {
       title: "Zhou'Blog",
       href: "https://type.zhoublog.xyz/",
       img: "https://cdn.jsdelivr.net/gh/Zhou216/Zhoublog/icons/MCGIF.gif",
       intro: " 随缘更新"
     },
]
friend19: [
 {
       title: "知我网",
       href: "https://gloom.top",
       img: "https://img.gloom.top/image/3a59e5f9fdd0.jpg",
       intro: "要像一颗微不足道的小星学习，可以微弱，但要有光"
     },
]




